language: node_js
node_js:
  - "0.8"
  - "0.10"
  - "0.11"
before_script:
  - npm install git://github.com/fluidsonic/node-coveralls.git#fix-absolute-paths
after_success:
  - coveralls < ./coverage/lcov.info
